sudo: required

services:
  - docker

before_install:
  - docker build -t aferracci/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aferracci/react-test npm test -- --coverage

after_success:
  - docker build -t aferracci/complex-client -f ./client/Dockerfile
  - docker build -t aferracci/complex-nginx -f ./nginx/Dockerfile
  - docker build -t aferracci/complex-server -f ./server/Dockerfile
  - docker build -t aferracci/complex-worker -f ./worker/Dockerfile
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push aferracci/complex-client
  - docker push aferracci/complex-nginx
  - docker push aferracci/complex-server
  - docker push aferracci/complex-worker
